version: '3'
services:
  asome-db:
    image: postgres:15-alpine
    container_name: asome_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - asome-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend (Strapi)
  asome-backend:
    container_name: asome_backend
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: asome-db 
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: bFJxmTrzMZ1tuSKuV7qVTw==,TlRu8IVYLC8diTILqGbj+w==,IuDibmTsUK0sv4unK3Eefw==,3+zX7cf5/TAKpEmUX1DTOw==
      API_TOKEN_SALT: pNS9W34ZN4n3dW0H81H92A==
      ADMIN_JWT_SECRET: /vtGvfDWkbwavbsFdPXmzA==
      TRANSFER_TOKEN_SALT: 7mFabl7756OljlAEfOkfAQ==
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/public/uploads:/opt/app/public/uploads
      - /opt/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - asome-db

volumes:
  asome-db-data: